- hosts: db
  handlers:
  - name: Redhat restart httpd
    service:
      name: "{{ service-name}}"
      state: restarted

- hosts: web
  handlers:
  - name: Debian restart apache
    service:
      name: "{{ service-name}}"
      state: restarted
  tasks:
  - include_tasks: "{{ ansible_os_family }}-web.yml"
